Repository Sylius/Sylius-Standard, pull requests merged in 2018-10, with the labels that each got.

#271 Fix Docker setup after moving to new Symfony / Flex directory structure
  docker-compose.yml
  docker/nginx/conf.d/default.conf
  docker/nginx/conf.d/default.dev.conf
  public/.htaccess
  src/Entity/.gitignore
  symfony.lock
Labels: Bug, Docker

#273 Fix error templates path
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Bug

#270 Fix: add coreutils to build-deps to be able to use nproc
  Dockerfile
Labels: Docker

#282 Upgrade security checker, move it to require-dev and run on Travis CI
  .travis.yml
  composer.json
  composer.lock
  config/packages/dev/security_checker.yaml
  config/packages/test/security_checker.yaml
  config/packages/test_cached/security_checker.yaml
Labels: Enhancement

#284 Add default "tests/" directory
  tests/.gitignore
Labels: Bug

#283 Change the theme directory from "app/themes/" to "themes/"
  config/packages/_sylius.yaml
  themes/.gitingore
Labels: Bug

#285 Do not load WebServerBundle on production
  config/bundles.php
Labels: Bug

#289 Move Flex from "require-dev" to "require"
  composer.json
  composer.lock
Labels: Bug
