Repository Sylius/Sylius-Standard, pull requests merged in 2019-05, with the labels that each got.

#339 [Maintenance] Upgrade minimal jquery version
  package.json
  yarn.lock
Labels: Maintenance

#342 Synchronize security.yaml with Sylius/Sylius
  config/packages/security.yaml
Labels: Bug

#344 Synchronize security.yaml with Sylius vol.2
  config/packages/security.yaml
Labels: Bug, Maintenance
