Repository Sylius/Sylius-Standard, pull requests merged in 2019-07, with the labels that each got.

#355 [README] Update docs links
  README.md
Labels: Documentation

#334 [Docker] Set the mailer to use the mailhog container
  docker-compose.yml
Labels: Docker

#360 [Config] Add missing media image folder
  .gitignore
  public/media/image/.gitkeep
Labels: Bug

#359 [Configuration] Missing php spec config
  phpspec.yaml.dist
Labels: Bug

#358 Don't mount mailhog maildir directory from host
  docker-compose.yml
Labels: Docker
