Repository Sylius/Sylius-Standard, pull requests merged in 2021-12, with the labels that each got.

#633 Add missing polishsymfonycommunity/symfony-mocker-container dependency
  composer.json
  config/services_test.yaml
  src/Kernel.php
Labels: Bug

#621 Update python package name in nodejs step
  Dockerfile
Labels: Bug, Docker

#625 Backport master changes on docker for 1.10
  Dockerfile
  docker-compose.yml
  docker/nginx/conf.d/default.conf
  docker/node/docker-entrypoint.sh
Labels: DX, Enhancement

#646 Alias branch 1.10-dev
  composer.json
Labels: Maintenance
