Repository Sylius/Sylius-Standard, pull requests merged in 2022-04, with the labels that each got.

#701 Fix 1.10 version problem
  .github/workflows/build.yml
  behat.yml.dist
  composer.json
  phpstan.neon
Labels: Bug, Maintenance

#679 Enable Sylius API in dev by default
  config/packages/dev/_sylius.yaml
Labels: DX, Enhancement

#694 [README] Add reasonable defaults configs for mailing and messenger to avoid production errors
  .env
Labels: Maintenance

#695 [README] Add link to official docs in installation section
  README.md
Labels: Maintenance

#691 New recommended way to run Symfony server
  README.md
Labels: Maintenance, Documentation

#616 Remove deprecated whitespace from tag filter
  .github/workflows/build.yml
  behat.yml.dist
Labels: Bug

#702 [Docker]Force no-interaction mode on installation
  Dockerfile
Labels: Bug, Docker

#703 [Docker]Define MySQL platform as linux/amd64
  docker-compose.yml
Labels: Bug, DX, Docker
