Repository Sylius/Sylius-Standard, pull requests merged in 2022-11, with the labels that each got.

#842 [docker] Simple queue worker
  docker-compose.prod.yml
Labels: Docker

#864 Use stable Sylius/Sylius and PayPalPlugin
  composer.json
Labels: Maintenance

#865 [Maintenance] Annotation changed to PHP Attributes in the Entity classes
  config/packages/doctrine.yaml
  src/Entity/Addressing/Address.php
  src/Entity/Addressing/Country.php
  src/Entity/Addressing/Province.php
  src/Entity/Addressing/Zone.php
  src/Entity/Addressing/ZoneMember.php
  src/Entity/Channel/Channel.php
  src/Entity/Channel/ChannelPricing.php
  src/Entity/Currency/Currency.php
  src/Entity/Currency/ExchangeRate.php
  src/Entity/Customer/Customer.php
  src/Entity/Customer/CustomerGroup.php
  src/Entity/Locale/Locale.php
  src/Entity/Order/Adjustment.php
  src/Entity/Order/Order.php
  src/Entity/Order/OrderItem.php
  src/Entity/Order/OrderItemUnit.php
  src/Entity/Order/OrderSequence.php
  src/Entity/Payment/GatewayConfig.php
  src/Entity/Payment/Payment.php
  src/Entity/Payment/PaymentMethod.php
  src/Entity/Payment/PaymentMethodTranslation.php
  src/Entity/Payment/PaymentSecurityToken.php
  src/Entity/Product/Product.php
  src/Entity/Product/ProductAssociation.php
  src/Entity/Product/ProductAssociationType.php
  src/Entity/Product/ProductAssociationTypeTranslation.php
  src/Entity/Product/ProductAttribute.php
  src/Entity/Product/ProductAttributeTranslation.php
  src/Entity/Product/ProductAttributeValue.php
  src/Entity/Product/ProductImage.php
  src/Entity/Product/ProductOption.php
  src/Entity/Product/ProductOptionTranslation.php
  src/Entity/Product/ProductOptionValue.php
  src/Entity/Product/ProductOptionValueTranslation.php
  src/Entity/Product/ProductReview.php
  src/Entity/Product/ProductTaxon.php
  src/Entity/Product/ProductTranslation.php
  src/Entity/Product/ProductVariant.php
  src/Entity/Product/ProductVariantTranslation.php
  src/Entity/Promotion/CatalogPromotion.php
  src/Entity/Promotion/CatalogPromotionAction.php
  src/Entity/Promotion/CatalogPromotionScope.php
  src/Entity/Promotion/Promotion.php
  src/Entity/Promotion/PromotionAction.php
  src/Entity/Promotion/PromotionCoupon.php
  src/Entity/Promotion/PromotionRule.php
  src/Entity/Shipping/Shipment.php
  src/Entity/Shipping/ShippingCategory.php
  src/Entity/Shipping/ShippingMethod.php
  src/Entity/Shipping/ShippingMethodTranslation.php
  src/Entity/Taxation/TaxCategory.php
  src/Entity/Taxation/TaxRate.php
  src/Entity/Taxonomy/Taxon.php
  src/Entity/Taxonomy/TaxonImage.php
  src/Entity/Taxonomy/TaxonTranslation.php
  src/Entity/User/AdminUser.php
  src/Entity/User/ShopUser.php
  src/Entity/User/UserOAuth.php
Labels: Maintenance

#866 Install only Sylius 1.11 on Sylius-Standard 1.11
  .github/workflows/build.yml
  composer.json
Labels: Bug, Maintenance

#867 [Behat] Change the base url in configuration
  behat.yml.dist
Labels: Bug

#845 [maintenance] Use the when@environment to reduce amount of config files
  config/packages/_sylius.yaml
  config/packages/dev/_sylius.yaml
  config/packages/dev/framework.yaml
  config/packages/dev/routing.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/framework.yaml
  config/packages/mailer.yaml
  config/packages/routing.yaml
  config/packages/staging/monolog.yaml
  config/packages/test/framework.yaml
  config/packages/test/mailer.yaml
  config/packages/test/web_profiler.yaml
  config/packages/test_cached/framework.yaml
  config/packages/test_cached/mailer.yaml
  config/packages/test_cached/twig.yaml
  config/packages/test_cached/web_profiler.yaml
  config/packages/twig.yaml
  config/packages/web_profiler.yaml
Labels: DX, Maintenance

#844 [docker] Update container's dependencies versions
  .github/workflows/build.yml
  Dockerfile
  composer.json
Labels: Maintenance, Docker

#877 [Maintenance] `sylius/sylius-rector` instead of `rector/rector`
  composer.json
Labels: Maintenance

#879 Bump PHPStan to ^1.8.4
  composer.json
Labels: DX, Maintenance

#881 Revert "[Maintenance] Annotation changed to PHP Attributes in the Entity classes"
  config/packages/doctrine.yaml
  src/Entity/Addressing/Address.php
  src/Entity/Addressing/Country.php
  src/Entity/Addressing/Province.php
  src/Entity/Addressing/Zone.php
  src/Entity/Addressing/ZoneMember.php
  src/Entity/Channel/Channel.php
  src/Entity/Channel/ChannelPricing.php
  src/Entity/Currency/Currency.php
  src/Entity/Currency/ExchangeRate.php
  src/Entity/Customer/Customer.php
  src/Entity/Customer/CustomerGroup.php
  src/Entity/Locale/Locale.php
  src/Entity/Order/Adjustment.php
  src/Entity/Order/Order.php
  src/Entity/Order/OrderItem.php
  src/Entity/Order/OrderItemUnit.php
  src/Entity/Order/OrderSequence.php
  src/Entity/Payment/GatewayConfig.php
  src/Entity/Payment/Payment.php
  src/Entity/Payment/PaymentMethod.php
  src/Entity/Payment/PaymentMethodTranslation.php
  src/Entity/Payment/PaymentSecurityToken.php
  src/Entity/Product/Product.php
  src/Entity/Product/ProductAssociation.php
  src/Entity/Product/ProductAssociationType.php
  src/Entity/Product/ProductAssociationTypeTranslation.php
  src/Entity/Product/ProductAttribute.php
  src/Entity/Product/ProductAttributeTranslation.php
  src/Entity/Product/ProductAttributeValue.php
  src/Entity/Product/ProductImage.php
  src/Entity/Product/ProductOption.php
  src/Entity/Product/ProductOptionTranslation.php
  src/Entity/Product/ProductOptionValue.php
  src/Entity/Product/ProductOptionValueTranslation.php
  src/Entity/Product/ProductReview.php
  src/Entity/Product/ProductTaxon.php
  src/Entity/Product/ProductTranslation.php
  src/Entity/Product/ProductVariant.php
  src/Entity/Product/ProductVariantTranslation.php
  src/Entity/Promotion/CatalogPromotion.php
  src/Entity/Promotion/CatalogPromotionAction.php
  src/Entity/Promotion/CatalogPromotionScope.php
  src/Entity/Promotion/Promotion.php
  src/Entity/Promotion/PromotionAction.php
  src/Entity/Promotion/PromotionCoupon.php
  src/Entity/Promotion/PromotionRule.php
  src/Entity/Shipping/Shipment.php
  src/Entity/Shipping/ShippingCategory.php
  src/Entity/Shipping/ShippingMethod.php
  src/Entity/Shipping/ShippingMethodTranslation.php
  src/Entity/Taxation/TaxCategory.php
  src/Entity/Taxation/TaxRate.php
  src/Entity/Taxonomy/Taxon.php
  src/Entity/Taxonomy/TaxonImage.php
  src/Entity/Taxonomy/TaxonTranslation.php
  src/Entity/User/AdminUser.php
  src/Entity/User/ShopUser.php
  src/Entity/User/UserOAuth.php
Labels: Bug

#873 [maintenance] - Ignore yarn.lock file
  .gitignore
  Dockerfile
  yarn.lock
Labels: Docker
