Repository Sylius/Sylius-Standard, pull requests merged in 2022-07, with the labels that each got.

#789 fix(composer): allow plugin for symfony flex
  composer.json
Labels: Bug, Maintenance

#791 fix(composer): allow plugin for symfony flex
  composer.json
Labels: Maintenance

#770 Remove firewall for dev routes
  config/packages/security.yaml
Labels: Maintenance, Enhancement

#795 [Maintenance][Composer] Code sniffer plugin turn off
  behat.yml.dist
  composer.json
  config/packages/security.yaml
Labels: Bug, Maintenance

#649 Make ports exposed by Docker configurable via env vars
  docker-compose.yml
Labels: Docker

#794 [docker]Ensure var/sessions is created
  docker/php/docker-entrypoint.sh
Labels: Docker

#806 Add missing overridden Catalog Promotions-related models
  composer.json
  config/packages/_sylius.yaml
  src/Entity/Promotion/CatalogPromotion.php
  src/Entity/Promotion/CatalogPromotionAction.php
  src/Entity/Promotion/CatalogPromotionScope.php
Labels: Bug
