Repository Sylius/Sylius-Standard, pull requests merged in 2022-01, with the labels that each got.

#644 [Docker] Update PHP and Node deps
  Dockerfile
Labels: DX, Maintenance

#643 [Docker] Remove python dependency
  Dockerfile
Labels: DX, Enhancement

#647 [Maintenance] Fix build & prepare it for Sylius v1.11
  .env
  .env.test
  .env.test_cached
  .github/workflows/build.yml
  behat.yml.dist
  config/packages/test_cached/web_profiler.yaml
Labels: Bug, Maintenance

#658 [Maintenance] Bring back schema validate
  .github/workflows/build.yml
Labels: DX, Enhancement

#659 Upgrade required version of PHP to 8.0
  composer.json
Labels: Maintenance

#663 Drop symfony4 support
  .github/workflows/build.yml
  composer.json
Labels: Maintenance

#666 [Docker] Bring back python2 dep
  Dockerfile
Labels: Bug, Docker
