Repository Sylius/Sylius-Standard, pull requests merged in 2023-04, with the labels that each got.

#905 [Conflict] Add conflict with symfony/framework-bundle:6.2.8
  CONFLICTS.md
  composer.json
Labels: Maintenance

#906 [Maintenance] Sylius Rector upgrade, override PayPal route
  composer.json
  config/routes/sylius_shop.yaml
  ecs.php
Labels: Bug, Maintenance

#903 [Docker] configuration: fix mailer dsn
  docker-compose.yml
Labels: Docker
