Repository Sylius/Sylius-Standard, pull requests merged in 2024-12, with the labels that each got.

#1031 Fix Platform.sh template
  .platform.app.yaml
Labels: Bug, Maintenance

#1086 Add sodium extension to Platform.sh config on 1.14
  .platform.app.yaml
Labels: Bug, Maintenance

#1087 Add sodium extension to Platform.sh config on 2.0
  .platform.app.yaml
Labels: Bug, Maintenance

#1090 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Maintenance

#1092 [Maintenance] Split CI builds to run faster
  .github/workflows/build.yml
  .github/workflows/ci_e2e-mysql.yaml
  .github/workflows/ci_static-checks.yaml
  .github/workflows/matrix.json
  symfony.lock
  templates/admin/javascripts.html.twig
Labels: Maintenance

#1093 [Docker] Adjust configuration for Sylius 2.0
  Dockerfile
  compose.override.dist.yml
  compose.yml
Labels: Docker
