Repository Sylius/Sylius-Standard, pull requests merged in 2024-02, with the labels that each got.

#941 Move Parameters to another file
  .github/workflows/build.yml
  config/packages/_sylius.yaml
  config/parameters.yaml
  config/services.yaml
Labels: Maintenance

#945 Conflict `behat/mink-selenium2-driver:>=1.7.0`
  CONFLICTS.md
  composer.json
Labels: Maintenance

#948 [Maintenance] Bump version of symfony/flex to ^2.4
  .github/workflows/build.yml
  composer.json
Labels: Maintenance

#936 PHP Attributes support in controllers
  config/routes/annotations.yaml
Labels: Enhancement

#949 Launch `Sylius 1.13` branch 🚀
  .github/workflows/build.yml
  .gitignore
  behat.yml.dist
  composer.json
  config/bundles.php
  config/packages/_sylius.yaml
  config/packages/nyholm_psr7.yaml
  config/packages/workflow.yaml
  config/routes.yaml
  config/routes/sylius_admin.yaml
  config/routes/sylius_shop.yaml
  docker-compose.prod.yml
  docker-compose.yml
  src/Entity/Channel/ChannelPriceHistoryConfig.php
  src/Entity/Channel/ChannelPricingLogEntry.php
  symfony.lock
  templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig
  templates/bundles/SyliusShopBundle/Checkout/SelectPayment/_choice.html.twig
  templates/bundles/SyliusShopBundle/Common/Order/_addresses.html.twig
Labels: Maintenance, Docker
