Repository Sylius/Sylius-Standard, pull requests merged in 2025-05, with the labels that each got.

#1131 [Maintenance] Set pdf generation to disabled by default
  config/packages/sylius_refund.yaml
Labels: Maintenance

#1133 Bump Sylius Rector
  composer.json
  phpstan.neon
Labels: Maintenance, Dependencies

#1132 Remove unnecessary Mollie overriding templates
  composer.json
  templates/bundles/SyliusAdminBundle/Layout/layout.html.twig
  templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig
  templates/bundles/SyliusAdminBundle/Product/Tab/_details.html.twig
  templates/bundles/SyliusAdminBundle/Shipment/Partial/_ship.html.twig
  templates/bundles/SyliusRefundPlugin/orderRefunds.html.twig
  templates/bundles/SyliusShopBundle/Checkout/_support.html.twig
  templates/bundles/SyliusShopBundle/Product/_info.html.twig
  templates/bundles/SyliusUiBundle/Layout/sidebar.html.twig
Labels: Enhancement, Dependencies

#1129 Fix dev firewall order
  config/packages/security.yaml
Labels: Maintenance
